name: geojson
description: Utilities to work with geojson data. Parser with a reactive api, search and geofencing
homepage: https://github.com/synw/geojson
version: 0.9.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  meta: ^1.1.8
  geopoint: 
    git: 
      url: git://github.com/AlexRivero/ModifiedFlutterPackages.git
      path: ModifiedFlutterPackages/geopoint
  iso: ^0.3.0
  geodesy: 
    git: 
      url: git://github.com/AlexRivero/ModifiedFlutterPackages.git
      path: ModifiedFlutterPackages/geodesy

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.4.1
